export const CART_SESSION_ITEM = "CART_SESSION_ITEM"
export const ADD_QUANTITY_TRANSACTION_CODE = "ADD_QUANTITY"
export const REDUCE_QUANTITY_TRANSACTION_CODE = "REDUCE_QUANTITY"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export type UPDATE_CART_TRANSACTION_CODE = "ADD_QUANTITY" | "REDUCE_QUANTITY" | "REMOVE_FROM_CART";
